# Site settings
title: YCM 2030
email: info@ycm2030.com
description: " Inspiration - Empowerment - Change"
baseurl: ""
url: "http://www.ycm2030.com"

# Build settings
markdown: kramdown
permalink: pretty
